from configuracion import Configuracion

bajo = Configuracion(1,1,4)
medio = Configuracion(2,2,6)
alto = Configuracion(2,3,8)

#FEDERICO
def menuConfig():
    pass

def menuJuego():
    pass

#FUNCIONES CONFIGURACION:
#   1.CAMBIAR PUNTOS
#   1.CAMBIAR BONUS
#   1.CAMBIAR INTENTOS
#   1.AGREGAR, QUITAR Y EDITAR PALABRAS


#FUNCIONES JUEGO:
#   1.PALABRA CODIFICADA
#   2.ESCOGER UNA PALABRA RANDOM DEPENDE DE LA DIFICULTAD
#   3.PINTAR PALABRA Y SUS PISTAS
#   4.SI ACERTO LA PALABRA DESACTIVARLA
#   5.SELECCIONAR LA COMPLEJIDAD
#   6.RESTAR INTENTOS